/*
 * This file is generated by jOOQ.
 */
package app.heap.tgto.db.tables.daos;


import app.heap.tgto.db.tables.Message;
import app.heap.tgto.db.tables.records.MessageRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MessageDao extends DAOImpl<MessageRecord, app.heap.tgto.db.tables.pojos.Message, Long> {

    /**
     * Create a new MessageDao without any configuration
     */
    public MessageDao() {
        super(Message.MESSAGE, app.heap.tgto.db.tables.pojos.Message.class);
    }

    /**
     * Create a new MessageDao with an attached configuration
     */
    public MessageDao(Configuration configuration) {
        super(Message.MESSAGE, app.heap.tgto.db.tables.pojos.Message.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(app.heap.tgto.db.tables.pojos.Message object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>message IN (values)</code>
     */
    public List<app.heap.tgto.db.tables.pojos.Message> fetchByMessage(String... values) {
        return fetch(Message.MESSAGE.MESSAGE_, values);
    }

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    public List<app.heap.tgto.db.tables.pojos.Message> fetchByCreated(Timestamp... values) {
        return fetch(Message.MESSAGE.CREATED, values);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<app.heap.tgto.db.tables.pojos.Message> fetchByUserId(Long... values) {
        return fetch(Message.MESSAGE.USER_ID, values);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<app.heap.tgto.db.tables.pojos.Message> fetchById(Long... values) {
        return fetch(Message.MESSAGE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public app.heap.tgto.db.tables.pojos.Message fetchOneById(Long value) {
        return fetchOne(Message.MESSAGE.ID, value);
    }
}
