/*
 * This file is generated by jOOQ.
 */
package app.heap.tgto.db;


import app.heap.tgto.db.tables.FlywaySchemaHistory;
import app.heap.tgto.db.tables.Message;
import app.heap.tgto.db.tables.TgUser;
import app.heap.tgto.db.tables.records.FlywaySchemaHistoryRecord;
import app.heap.tgto.db.tables.records.MessageRecord;
import app.heap.tgto.db.tables.records.TgUserRecord;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<MessageRecord, Long> IDENTITY_MESSAGE = Identities0.IDENTITY_MESSAGE;
    public static final Identity<TgUserRecord, Long> IDENTITY_TG_USER = Identities0.IDENTITY_TG_USER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = UniqueKeys0.FLYWAY_SCHEMA_HISTORY_PK;
    public static final UniqueKey<MessageRecord> MESSAGE_PKEY = UniqueKeys0.MESSAGE_PKEY;
    public static final UniqueKey<TgUserRecord> UNIQUE_TG_USER = UniqueKeys0.UNIQUE_TG_USER;
    public static final UniqueKey<TgUserRecord> TG_USER_PKEY = UniqueKeys0.TG_USER_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<MessageRecord, TgUserRecord> MESSAGE__MESSAGE_USER_ID_FKEY = ForeignKeys0.MESSAGE__MESSAGE_USER_ID_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<MessageRecord, Long> IDENTITY_MESSAGE = Internal.createIdentity(Message.MESSAGE, Message.MESSAGE.ID);
        public static Identity<TgUserRecord, Long> IDENTITY_TG_USER = Internal.createIdentity(TgUser.TG_USER, TgUser.TG_USER.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, "flyway_schema_history_pk", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK);
        public static final UniqueKey<MessageRecord> MESSAGE_PKEY = Internal.createUniqueKey(Message.MESSAGE, "message_pkey", Message.MESSAGE.ID);
        public static final UniqueKey<TgUserRecord> UNIQUE_TG_USER = Internal.createUniqueKey(TgUser.TG_USER, "unique_tg_user", TgUser.TG_USER.USER_ID);
        public static final UniqueKey<TgUserRecord> TG_USER_PKEY = Internal.createUniqueKey(TgUser.TG_USER, "tg_user_pkey", TgUser.TG_USER.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<MessageRecord, TgUserRecord> MESSAGE__MESSAGE_USER_ID_FKEY = Internal.createForeignKey(app.heap.tgto.db.Keys.UNIQUE_TG_USER, Message.MESSAGE, "message__message_user_id_fkey", Message.MESSAGE.USER_ID);
    }
}
