/*
 * This file is generated by jOOQ.
 */
package io.heapy.tgto.db.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.5"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TgUser implements Serializable {

    private static final long serialVersionUID = 1565221580;

    private String url;
    private Long userId;
    private Long id;

    public TgUser() {
    }

    public TgUser(TgUser value) {
        this.url = value.url;
        this.userId = value.userId;
        this.id = value.id;
    }

    public TgUser(
            String url,
            Long userId,
            Long id
    ) {
        this.url = url;
        this.userId = userId;
        this.id = id;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TgUser (");

        sb.append(url);
        sb.append(", ").append(userId);
        sb.append(", ").append(id);

        sb.append(")");
        return sb.toString();
    }
}
